/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.stackjudge.db;


import com.kbalazsworks.stackjudge.db.tables.Address;
import com.kbalazsworks.stackjudge.db.tables.Company;
import com.kbalazsworks.stackjudge.db.tables.CompanyOwnRequest;
import com.kbalazsworks.stackjudge.db.tables.CompanyOwner;
import com.kbalazsworks.stackjudge.db.tables.FlywaySchemaHistory;
import com.kbalazsworks.stackjudge.db.tables.GoogleStaticMapsCache;
import com.kbalazsworks.stackjudge.db.tables.Group;
import com.kbalazsworks.stackjudge.db.tables.Notification;
import com.kbalazsworks.stackjudge.db.tables.PersistenceLog;
import com.kbalazsworks.stackjudge.db.tables.ProtectedReviewLog;
import com.kbalazsworks.stackjudge.db.tables.Review;
import com.kbalazsworks.stackjudge.db.tables.Users;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.address</code>.
     */
    public static final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>public.company</code>.
     */
    public static final Company COMPANY = Company.COMPANY;

    /**
     * The table <code>public.company_own_request</code>.
     */
    public static final CompanyOwnRequest COMPANY_OWN_REQUEST = CompanyOwnRequest.COMPANY_OWN_REQUEST;

    /**
     * The table <code>public.company_owner</code>.
     */
    public static final CompanyOwner COMPANY_OWNER = CompanyOwner.COMPANY_OWNER;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.google_static_maps_cache</code>.
     */
    public static final GoogleStaticMapsCache GOOGLE_STATIC_MAPS_CACHE = GoogleStaticMapsCache.GOOGLE_STATIC_MAPS_CACHE;

    /**
     * The table <code>public.group</code>.
     */
    public static final Group GROUP = Group.GROUP;

    /**
     * The table <code>public.notification</code>.
     */
    public static final Notification NOTIFICATION = Notification.NOTIFICATION;

    /**
     * The table <code>public.persistence_log</code>.
     */
    public static final PersistenceLog PERSISTENCE_LOG = PersistenceLog.PERSISTENCE_LOG;

    /**
     * The table <code>public.protected_review_log</code>.
     */
    public static final ProtectedReviewLog PROTECTED_REVIEW_LOG = ProtectedReviewLog.PROTECTED_REVIEW_LOG;

    /**
     * The table <code>public.review</code>.
     */
    public static final Review REVIEW = Review.REVIEW;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
