FROM openjdk:17-alpine

ENV GOOGLE_MAPS_KEY=qwe
ENV HEALTH_CHECK_ENV_VAR_TEST="env var test"
ENV HTTP_CORS_ORIGINS=https://localhost:4200
ENV IS_SEARCH_BOX_LOG_ENABLED=false
ENV JAVAX_NET_SSL_TRUST_STORE_PASSWORD=password
ENV REDIS_ASPECT_CACHE_ENABLED=false
ENV SERVER_ENV=LOCAL
ENV SERVER_PORT=8181
ENV SERVER_SSL_ENABLED=true
ENV SERVER_SSL_KEY_STORE=classpath:keystore/v2/sjdev.p12
ENV SERVER_SSL_KEY_STORE_PASSWORD=password
ENV SITE_DOMAIN=https://localhost:8181
ENV SITE_FRONTEND_DOMAIN=http://localhost:4200
ENV SJ_IDS_FULL_HOST=https://localhost:5001
ENV SPRING_DATASOURCE_PASSWORD=admin_pass
ENV SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:54320/stackjudge
ENV SPRING_DATASOURCE_USERNAME=admin
ENV SPRING_REDIS_HOST=localhost
ENV SPRING_REDIS_PASSWORD=
ENV SPRING_REDIS_PORT=63790

COPY ./stackjudge-docker-latest.jar /project/

EXPOSE 8181

ENTRYPOINT ["java", "--enable-preview", "-jar", "/project/stackjudge-docker-latest.jar"]