name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: DEBUG

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: File system info
      run: |
        echo "===========> github.workspace var: ${{ github.workspace }}"
        echo "===========> pwd:"
        pwd
        echo "===========> ls -hal:"
        ls -hal
        echo "===========> ls -hal /src:"
        ls -hal ./src
        echo "===========> print generated settings.xml"
        cat ./settings.xml

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: zulu
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml --settings settings.xml -DskipTests=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

    - name: File system info
      run: |
        echo "===========> github.workspace var: ${{ github.workspace }}"
        echo "===========> pwd:"
        pwd
        echo "===========> ls -hal:"
        ls -hal
        echo "===========> ls -hal /src:"
        ls -hal ./src
        echo "===========> ls -hal /target:"
        ls -hal ./target
        echo "===========> print generated settings.xml"
        cat ./settings.xml

    - name: Temporarily save jar artifact
      uses: actions/upload-artifact@v2
      with:
        name: jar-artifact
        path: ${{ github.workspace }}/target/stackjudge-0.0.1-SNAPSHOT.jar
        retention-days: 1

#    - name: Login to GitHub Container Registry
#      uses: docker/login-action@v2
#      with:
#        registry: "ghcr.io"
#        username: "${{ github.repository_owner }}"
#        password: "${{ secrets.GITHUB_TOKEN }}"
#
#    - name: Set up QEMU
#      uses: docker/setup-qemu-action@v2
#
#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v2

    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: "push"
        format: "docker"
        owner: "stackjudge"
        repo: "stackjudge_backend"
        file: ${{ github.workspace }}/target/stackjudge-0.0.1-SNAPSHOT.jar