name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: DEBUG

jobs:
  build:
    runs-on: ubuntu-latest

    services:

      postgres:
        image: "postgres:14"
        container_name: postgres
        env:
          POSTGRES_USER=admin
          POSTGRES_PASSWORD=admin_pass
          POSTGRES_DB=stackjudge
          PGDATA=/data/postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: "redis:6.2.6"
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

    - uses: actions/checkout@v3

    - name: File system info
      run: |
        echo "===========> github.workspace var: ${{ github.workspace }}"
        echo "===========> pwd:"
        pwd
        echo "===========> ls -hal:"
        ls -hal
        echo "===========> ls -hal /src:"
        ls -hal ./src
        echo "===========> print generated settings.xml"
        cat ./settings.xml

    - name: Build docker image
      run: |
        docker build --tag stackjudge:latest .

    - name: Save docker image
      run: |
        docker save -o latest.docker stackjudge:latest

    - name: Push do Cloudsmith
      uses: cloudsmith-io/action@2f8578217e6fa9fe305977bb278057514bccd8ea
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: push
        format: docker
        owner: stackjudge
        repo: stackjudge_backend
        republish: true
        file: ./latest.docker
