name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: DEBUG

env:
  DOCKER_HUB_USERNAME: kbalazsworks

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: >
          [
            {
              "id": "central",
              "name": "https://repo1.maven.org/maven2",
              "url": "https://repo1.maven.org/maven2",
              "releases": {
                "enabled": "true",
                "updatePolicy": "always",
                "checksumPolicy": "fail"
              },
              "snapshots": {
                "enabled": "true",
                "updatePolicy": "always",
                "checksumPolicy": "fail"
              }
            },
            {
              "id": "github",
              "name": "https://maven.pkg.github.com/balazskrizsan/stackjudge_notification_sdk_java_maven,
              "url": "https://maven.pkg.github.com/balazskrizsan/stackjudge_notification_sdk_java_maven",
              "releases": {
                "enabled": "true",
                "updatePolicy": "always",
                "checksumPolicy": "fail"
              },
              "snapshots": {
                "enabled": "true",
                "updatePolicy": "always",
                "checksumPolicy": "fail"
              }
            }
          ]
        servers: >
          [
            {
              "id": "github",
              "username": "${github.repository_owner}",
              "password": "${secrets.GHP_KEY}",
              "configuration": {
                "httpConfiguration": {
                  "all": {
                    "usePreemptive": "true"
                  }
                }
              }
            }
          ]
        output_file: .m2/settings.xml

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: zulu
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

    - name: File system info
      run: |
        echo "===========> github.workspace var: ${{ github.workspace }}"
        echo "===========> pwd:"
        pwd
        echo "===========> ls -hal:"
        ls -hal
        echo "===========> ls -hal /src:"
        ls -hal ./src
        echo "===========> ls -hal /target:"
        ls -hal ./target

#    - name: Docker Login
#      uses: docker/login-action@v2
#      with:
#        username: "${{ env.DOCKER_HUB_USERNAME }}"
#        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
#
#    - name: Login to GitHub Container Registry
#      uses: docker/login-action@v2
#      with:
#        registry: "ghcr.io"
#        username: "${{ github.repository_owner }}"
#        password: "${{ secrets.GITHUB_TOKEN }}"

#    - name: Temporarily save jar artifact
#      uses: actions/upload-artifact@v2
#      with:
#        name: jar-artifact
#        path: ${{ github.workspace }}/target/stackjudge-0.0.1-SNAPSHOT.jar
#        retention-days: 1

#    - name: Build and push Docker image
#      uses: docker/build-push-action@v3
#      with:
#        context: .
#        push: true
#        tags: first_tag
#        labels: first_label