name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: DEBUG

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: File system info
      run: |
        echo "===========> github.workspace var: ${{ github.workspace }}"
        echo "===========> pwd:"
        pwd
        echo "===========> ls -hal:"
        ls -hal
        echo "===========> ls -hal /src:"
        ls -hal ./src
        echo "===========> print generated settings.xml"
        cat ./settings.xml

    - name: Build docker image
      run: |
        docker build --tag latest

    - name: Save docker image
      run: |
        docker save -o latest.docker

    - name: Push do Cloudsmith
      uses: cloudsmith-io/action@2f8578217e6fa9fe305977bb278057514bccd8ea
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: push
        format: docker
        owner: stackjudge
        repo: stackjudge_backend
        republish: true
        file: ./latest.docker
