/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.stackjudge.db.tables.records;


import com.kbalazsworks.stackjudge.db.tables.Company;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompanyRecord extends UpdatableRecordImpl<CompanyRecord> implements Record8<Long, String, String, Short, Short, String, LocalDateTime, String> {

    private static final long serialVersionUID = -1844524484;

    /**
     * Setter for <code>public.company.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.company.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.company.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.company.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.company.domain</code>.
     */
    public void setDomain(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.company.domain</code>.
     */
    public String getDomain() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.company.company_size_id</code>.
     */
    public void setCompanySizeId(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.company.company_size_id</code>.
     */
    public Short getCompanySizeId() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.company.it_size_id</code>.
     */
    public void setItSizeId(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.company.it_size_id</code>.
     */
    public Short getItSizeId() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>public.company.logo_path</code>.
     */
    public void setLogoPath(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.company.logo_path</code>.
     */
    public String getLogoPath() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.company.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.company.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.company.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.company.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, String, Short, Short, String, LocalDateTime, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, String, String, Short, Short, String, LocalDateTime, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Company.COMPANY.ID;
    }

    @Override
    public Field<String> field2() {
        return Company.COMPANY.NAME;
    }

    @Override
    public Field<String> field3() {
        return Company.COMPANY.DOMAIN;
    }

    @Override
    public Field<Short> field4() {
        return Company.COMPANY.COMPANY_SIZE_ID;
    }

    @Override
    public Field<Short> field5() {
        return Company.COMPANY.IT_SIZE_ID;
    }

    @Override
    public Field<String> field6() {
        return Company.COMPANY.LOGO_PATH;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Company.COMPANY.CREATED_AT;
    }

    @Override
    public Field<String> field8() {
        return Company.COMPANY.CREATED_BY;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDomain();
    }

    @Override
    public Short component4() {
        return getCompanySizeId();
    }

    @Override
    public Short component5() {
        return getItSizeId();
    }

    @Override
    public String component6() {
        return getLogoPath();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public String component8() {
        return getCreatedBy();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDomain();
    }

    @Override
    public Short value4() {
        return getCompanySizeId();
    }

    @Override
    public Short value5() {
        return getItSizeId();
    }

    @Override
    public String value6() {
        return getLogoPath();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public String value8() {
        return getCreatedBy();
    }

    @Override
    public CompanyRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public CompanyRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public CompanyRecord value3(String value) {
        setDomain(value);
        return this;
    }

    @Override
    public CompanyRecord value4(Short value) {
        setCompanySizeId(value);
        return this;
    }

    @Override
    public CompanyRecord value5(Short value) {
        setItSizeId(value);
        return this;
    }

    @Override
    public CompanyRecord value6(String value) {
        setLogoPath(value);
        return this;
    }

    @Override
    public CompanyRecord value7(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public CompanyRecord value8(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public CompanyRecord values(Long value1, String value2, String value3, Short value4, Short value5, String value6, LocalDateTime value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CompanyRecord
     */
    public CompanyRecord() {
        super(Company.COMPANY);
    }

    /**
     * Create a detached, initialised CompanyRecord
     */
    public CompanyRecord(Long id, String name, String domain, Short companySizeId, Short itSizeId, String logoPath, LocalDateTime createdAt, String createdBy) {
        super(Company.COMPANY);

        set(0, id);
        set(1, name);
        set(2, domain);
        set(3, companySizeId);
        set(4, itSizeId);
        set(5, logoPath);
        set(6, createdAt);
        set(7, createdBy);
    }
}
