/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.stackjudge.db.tables.records;


import com.kbalazsworks.stackjudge.db.tables.CompanyOwnRequest;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompanyOwnRequestRecord extends UpdatableRecordImpl<CompanyOwnRequestRecord> implements Record4<Long, Long, String, LocalDateTime> {

    private static final long serialVersionUID = -1891679907;

    /**
     * Setter for <code>public.company_own_request.requester_user_id</code>.
     */
    public void setRequesterUserId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.company_own_request.requester_user_id</code>.
     */
    public Long getRequesterUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.company_own_request.requested_company_id</code>.
     */
    public void setRequestedCompanyId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.company_own_request.requested_company_id</code>.
     */
    public Long getRequestedCompanyId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.company_own_request.secret</code>.
     */
    public void setSecret(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.company_own_request.secret</code>.
     */
    public String getSecret() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.company_own_request.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.company_own_request.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, String, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Long, String, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return CompanyOwnRequest.COMPANY_OWN_REQUEST.REQUESTER_USER_ID;
    }

    @Override
    public Field<Long> field2() {
        return CompanyOwnRequest.COMPANY_OWN_REQUEST.REQUESTED_COMPANY_ID;
    }

    @Override
    public Field<String> field3() {
        return CompanyOwnRequest.COMPANY_OWN_REQUEST.SECRET;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return CompanyOwnRequest.COMPANY_OWN_REQUEST.CREATED_AT;
    }

    @Override
    public Long component1() {
        return getRequesterUserId();
    }

    @Override
    public Long component2() {
        return getRequestedCompanyId();
    }

    @Override
    public String component3() {
        return getSecret();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public Long value1() {
        return getRequesterUserId();
    }

    @Override
    public Long value2() {
        return getRequestedCompanyId();
    }

    @Override
    public String value3() {
        return getSecret();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public CompanyOwnRequestRecord value1(Long value) {
        setRequesterUserId(value);
        return this;
    }

    @Override
    public CompanyOwnRequestRecord value2(Long value) {
        setRequestedCompanyId(value);
        return this;
    }

    @Override
    public CompanyOwnRequestRecord value3(String value) {
        setSecret(value);
        return this;
    }

    @Override
    public CompanyOwnRequestRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public CompanyOwnRequestRecord values(Long value1, Long value2, String value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CompanyOwnRequestRecord
     */
    public CompanyOwnRequestRecord() {
        super(CompanyOwnRequest.COMPANY_OWN_REQUEST);
    }

    /**
     * Create a detached, initialised CompanyOwnRequestRecord
     */
    public CompanyOwnRequestRecord(Long requesterUserId, Long requestedCompanyId, String secret, LocalDateTime createdAt) {
        super(CompanyOwnRequest.COMPANY_OWN_REQUEST);

        set(0, requesterUserId);
        set(1, requestedCompanyId);
        set(2, secret);
        set(3, createdAt);
    }
}
