/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.stackjudge.db.tables.records;


import com.kbalazsworks.stackjudge.db.tables.Company;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompanyRecord extends UpdatableRecordImpl<CompanyRecord> implements Record6<Long, String, Short, Short, LocalDateTime, Long> {

    private static final long serialVersionUID = 1588574395;

    /**
     * Setter for <code>public.company.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.company.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.company.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.company.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.company.company_size_id</code>.
     */
    public void setCompanySizeId(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.company.company_size_id</code>.
     */
    public Short getCompanySizeId() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.company.it_size_id</code>.
     */
    public void setItSizeId(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.company.it_size_id</code>.
     */
    public Short getItSizeId() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.company.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.company.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.company.created_by</code>.
     */
    public void setCreatedBy(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.company.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, Short, Short, LocalDateTime, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, Short, Short, LocalDateTime, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Company.COMPANY.ID;
    }

    @Override
    public Field<String> field2() {
        return Company.COMPANY.NAME;
    }

    @Override
    public Field<Short> field3() {
        return Company.COMPANY.COMPANY_SIZE_ID;
    }

    @Override
    public Field<Short> field4() {
        return Company.COMPANY.IT_SIZE_ID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Company.COMPANY.CREATED_AT;
    }

    @Override
    public Field<Long> field6() {
        return Company.COMPANY.CREATED_BY;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Short component3() {
        return getCompanySizeId();
    }

    @Override
    public Short component4() {
        return getItSizeId();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public Long component6() {
        return getCreatedBy();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Short value3() {
        return getCompanySizeId();
    }

    @Override
    public Short value4() {
        return getItSizeId();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public Long value6() {
        return getCreatedBy();
    }

    @Override
    public CompanyRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public CompanyRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public CompanyRecord value3(Short value) {
        setCompanySizeId(value);
        return this;
    }

    @Override
    public CompanyRecord value4(Short value) {
        setItSizeId(value);
        return this;
    }

    @Override
    public CompanyRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public CompanyRecord value6(Long value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public CompanyRecord values(Long value1, String value2, Short value3, Short value4, LocalDateTime value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CompanyRecord
     */
    public CompanyRecord() {
        super(Company.COMPANY);
    }

    /**
     * Create a detached, initialised CompanyRecord
     */
    public CompanyRecord(Long id, String name, Short companySizeId, Short itSizeId, LocalDateTime createdAt, Long createdBy) {
        super(Company.COMPANY);

        set(0, id);
        set(1, name);
        set(2, companySizeId);
        set(3, itSizeId);
        set(4, createdAt);
        set(5, createdBy);
    }
}
