/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.stackjudge.db.tables.records;


import com.kbalazsworks.stackjudge.db.tables.Group;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupRecord extends UpdatableRecordImpl<GroupRecord> implements Record8<Long, Long, Long, String, Short, Short, LocalDateTime, Long> {

    private static final long serialVersionUID = 1100861567;

    /**
     * Setter for <code>public.group.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.group.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.group.parent_id</code>.
     */
    public void setParentId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.group.parent_id</code>.
     */
    public Long getParentId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.group.company_id</code>.
     */
    public void setCompanyId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.group.company_id</code>.
     */
    public Long getCompanyId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.group.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.group.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.group.type_id</code>.
     */
    public void setTypeId(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.group.type_id</code>.
     */
    public Short getTypeId() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>public.group.members_on_group_id</code>.
     */
    public void setMembersOnGroupId(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.group.members_on_group_id</code>.
     */
    public Short getMembersOnGroupId() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>public.group.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.group.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.group.created_by</code>.
     */
    public void setCreatedBy(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.group.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Long, Long, String, Short, Short, LocalDateTime, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Long, Long, String, Short, Short, LocalDateTime, Long> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Group.GROUP.ID;
    }

    @Override
    public Field<Long> field2() {
        return Group.GROUP.PARENT_ID;
    }

    @Override
    public Field<Long> field3() {
        return Group.GROUP.COMPANY_ID;
    }

    @Override
    public Field<String> field4() {
        return Group.GROUP.NAME;
    }

    @Override
    public Field<Short> field5() {
        return Group.GROUP.TYPE_ID;
    }

    @Override
    public Field<Short> field6() {
        return Group.GROUP.MEMBERS_ON_GROUP_ID;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Group.GROUP.CREATED_AT;
    }

    @Override
    public Field<Long> field8() {
        return Group.GROUP.CREATED_BY;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getParentId();
    }

    @Override
    public Long component3() {
        return getCompanyId();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public Short component5() {
        return getTypeId();
    }

    @Override
    public Short component6() {
        return getMembersOnGroupId();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public Long component8() {
        return getCreatedBy();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getParentId();
    }

    @Override
    public Long value3() {
        return getCompanyId();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public Short value5() {
        return getTypeId();
    }

    @Override
    public Short value6() {
        return getMembersOnGroupId();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public Long value8() {
        return getCreatedBy();
    }

    @Override
    public GroupRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public GroupRecord value2(Long value) {
        setParentId(value);
        return this;
    }

    @Override
    public GroupRecord value3(Long value) {
        setCompanyId(value);
        return this;
    }

    @Override
    public GroupRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public GroupRecord value5(Short value) {
        setTypeId(value);
        return this;
    }

    @Override
    public GroupRecord value6(Short value) {
        setMembersOnGroupId(value);
        return this;
    }

    @Override
    public GroupRecord value7(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public GroupRecord value8(Long value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public GroupRecord values(Long value1, Long value2, Long value3, String value4, Short value5, Short value6, LocalDateTime value7, Long value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GroupRecord
     */
    public GroupRecord() {
        super(Group.GROUP);
    }

    /**
     * Create a detached, initialised GroupRecord
     */
    public GroupRecord(Long id, Long parentId, Long companyId, String name, Short typeId, Short membersOnGroupId, LocalDateTime createdAt, Long createdBy) {
        super(Group.GROUP);

        set(0, id);
        set(1, parentId);
        set(2, companyId);
        set(3, name);
        set(4, typeId);
        set(5, membersOnGroupId);
        set(6, createdAt);
        set(7, createdBy);
    }
}
