/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.stackjudge.db.tables.records;


import com.kbalazsworks.stackjudge.db.tables.Notification;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationRecord extends UpdatableRecordImpl<NotificationRecord> implements Record6<Long, Long, Short, JSONB, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -131175249;

    /**
     * Setter for <code>public.notification.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.notification.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.notification.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.notification.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.notification.type</code>.
     */
    public void setType(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.notification.type</code>.
     */
    public Short getType() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.notification.data</code>.
     */
    public void setData(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.notification.data</code>.
     */
    public JSONB getData() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>public.notification.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.notification.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.notification.viewed_at</code>.
     */
    public void setViewedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.notification.viewed_at</code>.
     */
    public LocalDateTime getViewedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Short, JSONB, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Short, JSONB, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Notification.NOTIFICATION.ID;
    }

    @Override
    public Field<Long> field2() {
        return Notification.NOTIFICATION.USER_ID;
    }

    @Override
    public Field<Short> field3() {
        return Notification.NOTIFICATION.TYPE;
    }

    @Override
    public Field<JSONB> field4() {
        return Notification.NOTIFICATION.DATA;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Notification.NOTIFICATION.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Notification.NOTIFICATION.VIEWED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public Short component3() {
        return getType();
    }

    @Override
    public JSONB component4() {
        return getData();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component6() {
        return getViewedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public Short value3() {
        return getType();
    }

    @Override
    public JSONB value4() {
        return getData();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value6() {
        return getViewedAt();
    }

    @Override
    public NotificationRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public NotificationRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public NotificationRecord value3(Short value) {
        setType(value);
        return this;
    }

    @Override
    public NotificationRecord value4(JSONB value) {
        setData(value);
        return this;
    }

    @Override
    public NotificationRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public NotificationRecord value6(LocalDateTime value) {
        setViewedAt(value);
        return this;
    }

    @Override
    public NotificationRecord values(Long value1, Long value2, Short value3, JSONB value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotificationRecord
     */
    public NotificationRecord() {
        super(Notification.NOTIFICATION);
    }

    /**
     * Create a detached, initialised NotificationRecord
     */
    public NotificationRecord(Long id, Long userId, Short type, JSONB data, LocalDateTime createdAt, LocalDateTime viewedAt) {
        super(Notification.NOTIFICATION);

        set(0, id);
        set(1, userId);
        set(2, type);
        set(3, data);
        set(4, createdAt);
        set(5, viewedAt);
    }
}
