/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.stackjudge.db.tables.records;


import com.kbalazsworks.stackjudge.db.tables.PersistenceLog;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersistenceLogRecord extends UpdatableRecordImpl<PersistenceLogRecord> implements Record4<Long, Short, JSONB, LocalDateTime> {

    private static final long serialVersionUID = -742065121;

    /**
     * Setter for <code>public.persistence_log.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.persistence_log.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.persistence_log.type</code>.
     */
    public void setType(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.persistence_log.type</code>.
     */
    public Short getType() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>public.persistence_log.data</code>.
     */
    public void setData(JSONB value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.persistence_log.data</code>.
     */
    public JSONB getData() {
        return (JSONB) get(2);
    }

    /**
     * Setter for <code>public.persistence_log.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.persistence_log.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Short, JSONB, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Short, JSONB, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return PersistenceLog.PERSISTENCE_LOG.ID;
    }

    @Override
    public Field<Short> field2() {
        return PersistenceLog.PERSISTENCE_LOG.TYPE;
    }

    @Override
    public Field<JSONB> field3() {
        return PersistenceLog.PERSISTENCE_LOG.DATA;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return PersistenceLog.PERSISTENCE_LOG.CREATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Short component2() {
        return getType();
    }

    @Override
    public JSONB component3() {
        return getData();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Short value2() {
        return getType();
    }

    @Override
    public JSONB value3() {
        return getData();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public PersistenceLogRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PersistenceLogRecord value2(Short value) {
        setType(value);
        return this;
    }

    @Override
    public PersistenceLogRecord value3(JSONB value) {
        setData(value);
        return this;
    }

    @Override
    public PersistenceLogRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public PersistenceLogRecord values(Long value1, Short value2, JSONB value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PersistenceLogRecord
     */
    public PersistenceLogRecord() {
        super(PersistenceLog.PERSISTENCE_LOG);
    }

    /**
     * Create a detached, initialised PersistenceLogRecord
     */
    public PersistenceLogRecord(Long id, Short type, JSONB data, LocalDateTime createdAt) {
        super(PersistenceLog.PERSISTENCE_LOG);

        set(0, id);
        set(1, type);
        set(2, data);
        set(3, createdAt);
    }
}
