/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.stackjudge.db.tables.records;


import com.kbalazsworks.stackjudge.db.tables.ProtectedReviewLog;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProtectedReviewLogRecord extends UpdatableRecordImpl<ProtectedReviewLogRecord> implements Record4<Long, Long, Long, LocalDateTime> {

    private static final long serialVersionUID = -662223863;

    /**
     * Setter for <code>public.protected_review_log.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.protected_review_log.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.protected_review_log.viewer_user_id</code>.
     */
    public void setViewerUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.protected_review_log.viewer_user_id</code>.
     */
    public Long getViewerUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.protected_review_log.review_id</code>.
     */
    public void setReviewId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.protected_review_log.review_id</code>.
     */
    public Long getReviewId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.protected_review_log.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.protected_review_log.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, Long, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Long, Long, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ProtectedReviewLog.PROTECTED_REVIEW_LOG.ID;
    }

    @Override
    public Field<Long> field2() {
        return ProtectedReviewLog.PROTECTED_REVIEW_LOG.VIEWER_USER_ID;
    }

    @Override
    public Field<Long> field3() {
        return ProtectedReviewLog.PROTECTED_REVIEW_LOG.REVIEW_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return ProtectedReviewLog.PROTECTED_REVIEW_LOG.CREATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getViewerUserId();
    }

    @Override
    public Long component3() {
        return getReviewId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getViewerUserId();
    }

    @Override
    public Long value3() {
        return getReviewId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public ProtectedReviewLogRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ProtectedReviewLogRecord value2(Long value) {
        setViewerUserId(value);
        return this;
    }

    @Override
    public ProtectedReviewLogRecord value3(Long value) {
        setReviewId(value);
        return this;
    }

    @Override
    public ProtectedReviewLogRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ProtectedReviewLogRecord values(Long value1, Long value2, Long value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProtectedReviewLogRecord
     */
    public ProtectedReviewLogRecord() {
        super(ProtectedReviewLog.PROTECTED_REVIEW_LOG);
    }

    /**
     * Create a detached, initialised ProtectedReviewLogRecord
     */
    public ProtectedReviewLogRecord(Long id, Long viewerUserId, Long reviewId, LocalDateTime createdAt) {
        super(ProtectedReviewLog.PROTECTED_REVIEW_LOG);

        set(0, id);
        set(1, viewerUserId);
        set(2, reviewId);
        set(3, createdAt);
    }
}
