/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.stackjudge.db.tables.records;


import com.kbalazsworks.stackjudge.db.tables.Review;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReviewRecord extends UpdatableRecordImpl<ReviewRecord> implements Record7<Long, Long, Short, Short, String, LocalDateTime, String> {

    private static final long serialVersionUID = -846240528;

    /**
     * Setter for <code>public.review.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.review.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.review.group_id</code>.
     */
    public void setGroupId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.review.group_id</code>.
     */
    public Long getGroupId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.review.visibility</code>.
     */
    public void setVisibility(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.review.visibility</code>.
     */
    public Short getVisibility() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.review.rate</code>.
     */
    public void setRate(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.review.rate</code>.
     */
    public Short getRate() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.review.review</code>.
     */
    public void setReview(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.review.review</code>.
     */
    public String getReview() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.review.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.review.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.review.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.review.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, Short, Short, String, LocalDateTime, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, Short, Short, String, LocalDateTime, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Review.REVIEW.ID;
    }

    @Override
    public Field<Long> field2() {
        return Review.REVIEW.GROUP_ID;
    }

    @Override
    public Field<Short> field3() {
        return Review.REVIEW.VISIBILITY;
    }

    @Override
    public Field<Short> field4() {
        return Review.REVIEW.RATE;
    }

    @Override
    public Field<String> field5() {
        return Review.REVIEW.REVIEW_;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Review.REVIEW.CREATED_AT;
    }

    @Override
    public Field<String> field7() {
        return Review.REVIEW.CREATED_BY;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getGroupId();
    }

    @Override
    public Short component3() {
        return getVisibility();
    }

    @Override
    public Short component4() {
        return getRate();
    }

    @Override
    public String component5() {
        return getReview();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedAt();
    }

    @Override
    public String component7() {
        return getCreatedBy();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getGroupId();
    }

    @Override
    public Short value3() {
        return getVisibility();
    }

    @Override
    public Short value4() {
        return getRate();
    }

    @Override
    public String value5() {
        return getReview();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedAt();
    }

    @Override
    public String value7() {
        return getCreatedBy();
    }

    @Override
    public ReviewRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ReviewRecord value2(Long value) {
        setGroupId(value);
        return this;
    }

    @Override
    public ReviewRecord value3(Short value) {
        setVisibility(value);
        return this;
    }

    @Override
    public ReviewRecord value4(Short value) {
        setRate(value);
        return this;
    }

    @Override
    public ReviewRecord value5(String value) {
        setReview(value);
        return this;
    }

    @Override
    public ReviewRecord value6(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ReviewRecord value7(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public ReviewRecord values(Long value1, Long value2, Short value3, Short value4, String value5, LocalDateTime value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReviewRecord
     */
    public ReviewRecord() {
        super(Review.REVIEW);
    }

    /**
     * Create a detached, initialised ReviewRecord
     */
    public ReviewRecord(Long id, Long groupId, Short visibility, Short rate, String review, LocalDateTime createdAt, String createdBy) {
        super(Review.REVIEW);

        set(0, id);
        set(1, groupId);
        set(2, visibility);
        set(3, rate);
        set(4, review);
        set(5, createdAt);
        set(6, createdBy);
    }
}
