/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.stackjudge.db.tables.records;


import com.kbalazsworks.stackjudge.db.tables.Users;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record1<String> {

    private static final long serialVersionUID = -996965835;

    /**
     * Setter for <code>public.users.ids_user_id</code>.
     */
    public void setIdsUserId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.users.ids_user_id</code>.
     */
    public String getIdsUserId() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Users.USERS.IDS_USER_ID;
    }

    @Override
    public String component1() {
        return getIdsUserId();
    }

    @Override
    public String value1() {
        return getIdsUserId();
    }

    @Override
    public UsersRecord value1(String value) {
        setIdsUserId(value);
        return this;
    }

    @Override
    public UsersRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(String idsUserId) {
        super(Users.USERS);

        set(0, idsUserId);
    }
}
