/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.stackjudge.db.tables.records;


import com.kbalazsworks.stackjudge.db.tables.Users;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record9<Long, Boolean, Boolean, String, String, String, String, Long, String> {

    private static final long serialVersionUID = -852788058;

    /**
     * Setter for <code>public.users.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.users.is_email_user</code>.
     */
    public void setIsEmailUser(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.users.is_email_user</code>.
     */
    public Boolean getIsEmailUser() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.users.is_facebook_user</code>.
     */
    public void setIsFacebookUser(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.users.is_facebook_user</code>.
     */
    public Boolean getIsFacebookUser() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.users.profile_picture_url</code>.
     */
    public void setProfilePictureUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.users.profile_picture_url</code>.
     */
    public String getProfilePictureUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.users.username</code>.
     */
    public void setUsername(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.users.username</code>.
     */
    public String getUsername() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.users.password</code>.
     */
    public void setPassword(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.users.password</code>.
     */
    public String getPassword() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.users.facebook_access_token</code>.
     */
    public void setFacebookAccessToken(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.users.facebook_access_token</code>.
     */
    public String getFacebookAccessToken() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.users.facebook_id</code>.
     */
    public void setFacebookId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.users.facebook_id</code>.
     */
    public Long getFacebookId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.users.pushover_user_token</code>.
     */
    public void setPushoverUserToken(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.users.pushover_user_token</code>.
     */
    public String getPushoverUserToken() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Boolean, Boolean, String, String, String, String, Long, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, Boolean, Boolean, String, String, String, String, Long, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Users.USERS.ID;
    }

    @Override
    public Field<Boolean> field2() {
        return Users.USERS.IS_EMAIL_USER;
    }

    @Override
    public Field<Boolean> field3() {
        return Users.USERS.IS_FACEBOOK_USER;
    }

    @Override
    public Field<String> field4() {
        return Users.USERS.PROFILE_PICTURE_URL;
    }

    @Override
    public Field<String> field5() {
        return Users.USERS.USERNAME;
    }

    @Override
    public Field<String> field6() {
        return Users.USERS.PASSWORD;
    }

    @Override
    public Field<String> field7() {
        return Users.USERS.FACEBOOK_ACCESS_TOKEN;
    }

    @Override
    public Field<Long> field8() {
        return Users.USERS.FACEBOOK_ID;
    }

    @Override
    public Field<String> field9() {
        return Users.USERS.PUSHOVER_USER_TOKEN;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Boolean component2() {
        return getIsEmailUser();
    }

    @Override
    public Boolean component3() {
        return getIsFacebookUser();
    }

    @Override
    public String component4() {
        return getProfilePictureUrl();
    }

    @Override
    public String component5() {
        return getUsername();
    }

    @Override
    public String component6() {
        return getPassword();
    }

    @Override
    public String component7() {
        return getFacebookAccessToken();
    }

    @Override
    public Long component8() {
        return getFacebookId();
    }

    @Override
    public String component9() {
        return getPushoverUserToken();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Boolean value2() {
        return getIsEmailUser();
    }

    @Override
    public Boolean value3() {
        return getIsFacebookUser();
    }

    @Override
    public String value4() {
        return getProfilePictureUrl();
    }

    @Override
    public String value5() {
        return getUsername();
    }

    @Override
    public String value6() {
        return getPassword();
    }

    @Override
    public String value7() {
        return getFacebookAccessToken();
    }

    @Override
    public Long value8() {
        return getFacebookId();
    }

    @Override
    public String value9() {
        return getPushoverUserToken();
    }

    @Override
    public UsersRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UsersRecord value2(Boolean value) {
        setIsEmailUser(value);
        return this;
    }

    @Override
    public UsersRecord value3(Boolean value) {
        setIsFacebookUser(value);
        return this;
    }

    @Override
    public UsersRecord value4(String value) {
        setProfilePictureUrl(value);
        return this;
    }

    @Override
    public UsersRecord value5(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public UsersRecord value6(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UsersRecord value7(String value) {
        setFacebookAccessToken(value);
        return this;
    }

    @Override
    public UsersRecord value8(Long value) {
        setFacebookId(value);
        return this;
    }

    @Override
    public UsersRecord value9(String value) {
        setPushoverUserToken(value);
        return this;
    }

    @Override
    public UsersRecord values(Long value1, Boolean value2, Boolean value3, String value4, String value5, String value6, String value7, Long value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Long id, Boolean isEmailUser, Boolean isFacebookUser, String profilePictureUrl, String username, String password, String facebookAccessToken, Long facebookId, String pushoverUserToken) {
        super(Users.USERS);

        set(0, id);
        set(1, isEmailUser);
        set(2, isFacebookUser);
        set(3, profilePictureUrl);
        set(4, username);
        set(5, password);
        set(6, facebookAccessToken);
        set(7, facebookId);
        set(8, pushoverUserToken);
    }
}
